version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: aspnet_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "booking_ticket"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3308:3308"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backendnet

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: backend:latest
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=booking_ticket;User=root;Password=mysql;"
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./backend:/src/backend:cached
    networks:
      - backendnet

volumes:
  mysql_data:

networks:
  backendnet:
    driver: bridge
